
import { registerLanguage } from '../services/i18n';

const en = {
    common: {
        loading: 'Loading...',
        search: 'Search (use #tags)...',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        yes: 'Yes',
        no: 'No',
        ok: 'OK',
        error: 'Error',
        success: 'Success',
        confirm_delete: 'Move to trash?',
        confirm_perm_delete: 'Permanently delete? This cannot be undone!',
        confirm_discard: 'Entry will be moved to trash. Continue?',
        confirm_discard_changes: 'Discard changes? Entry will not be saved.',
        confirm_action: 'Are you sure?',
        unsaved_changes: 'Unsaved changes! If you leave, changes since the last manual or auto-save will be lost. Are you sure?',
        draft: 'Draft',
        trash: 'Trash',
        restore: 'Restore',
        perm_delete: 'Permanently Delete',
        empty_trash: 'Trash is empty.',
        empty_trash_btn: 'Empty Trash',
        confirm_empty_trash: 'Are you sure you want to permanently delete ALL items in trash?'
    },
    category: {
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
        yearly: 'Yearly'
    },
    subcats: {
        general: 'About my day',
        health: 'Health',
        friends: 'Friendship',
        business: 'Business Growth',
        finance: 'Financial Independence',
        family: 'Family',
        personal: 'Personal Development',
        goals: 'Goals',
        dreams: 'Plans & Dreams',
        achieved: 'Achieved Goals'
    },
    weather: {
        wmo_0: 'Clear sky',
        wmo_1: 'Mainly clear',
        wmo_2: 'Partly cloudy',
        wmo_3: 'Overcast',
        wmo_45: 'Fog',
        wmo_48: 'Depositing rime fog',
        wmo_51: 'Drizzle: Light',
        wmo_53: 'Drizzle: Moderate',
        wmo_55: 'Drizzle: Dense',
        wmo_56: 'Freezing Drizzle: Light',
        wmo_57: 'Freezing Drizzle: Dense',
        wmo_61: 'Rain: Slight',
        wmo_63: 'Rain: Moderate',
        wmo_65: 'Rain: Heavy',
        wmo_66: 'Freezing Rain: Light',
        wmo_67: 'Freezing Rain: Heavy',
        wmo_71: 'Snow fall: Slight',
        wmo_73: 'Snow fall: Moderate',
        wmo_75: 'Snow fall: Heavy',
        wmo_77: 'Snow grains',
        wmo_80: 'Rain showers: Slight',
        wmo_81: 'Rain showers: Moderate',
        wmo_82: 'Rain showers: Violent',
        wmo_85: 'Snow showers: Slight',
        wmo_86: 'Snow showers: Heavy',
        wmo_95: 'Thunderstorm',
        wmo_96: 'Thunderstorm with slight hail',
        wmo_99: 'Thunderstorm with heavy hail'
    },
    nav: {
        map: 'Map',
        gallery: 'Gallery',
        tags: 'Tags',
        stats: 'Statistics',
        on_this_day: 'On This Day',
        settings: 'Settings',
        deploy: 'Deploy',
        export: 'Export / Import',
        logout: 'Log Out',
        login: 'Admin Login',
        entries: 'Entries',
        questions: 'Questions',
        habits: 'Habits',
        appearance: 'Appearance',
        menu: 'Menu',
        trash: 'Trash'
    },
    filters: {
        title: 'Detailed Filters',
        date_start: 'Start Date',
        date_end: 'End Date',
        mood: 'Mood',
        has_photo: 'Has Photo',
        clear: 'Clear Filters'
    },
    stats: {
        title: 'Statistics',
        total_entries: 'Total Entries',
        current_streak: 'Current Streak',
        longest_streak: 'Longest Streak',
        mood_distribution: 'Mood Distribution',
        activity_heatmap: 'Activity (Last 12 Months)',
        no_data: 'Not enough data for statistics.',
        words: 'Words',
        chars: 'Chars',
        locations: 'Locations',
        top_locations: 'Top Visited Places',
        longest_entry: 'Longest Entry',
        correlations: 'Insights & Correlations',
        weather_mood: 'Weather & Mood',
        day_mood: 'Days & Mood',
        insight_weather: 'Most frequent in {weather} weather:',
        insight_day: 'Most frequent on {day}s:',
        streak_title: 'Perseverance & Momentum',
        streak_subtitle: 'Consistency is the key to success.',
        calendar_view: 'Calendar View'
    },
    templates: {
        title: 'Templates',
        save_current: 'Save current as template',
        load: 'Load template',
        name_placeholder: 'Template name (e.g. Gym Log)',
        confirm_load: 'This will overwrite current questions. Continue?',
        empty: 'No saved templates.',
        saved: 'Template saved!',
        deleted: 'Template deleted.',
        set_default: 'Set as Default',
        is_default: '(Default)'
    },
    theme: {
        title: 'Theme Editor',
        subtitle: 'Choose your preferred style or create your own.',
        presets: 'Presets',
        create: 'Creator',
        typography: 'Typography',
        weather_tab: 'Weather Icons',
        emoji_tab: 'Mood',
        secret_tab: 'Secret (Holidays)',
        weather_desc: 'Select how weather icons appear throughout the app.',
        emoji_desc: 'Select the visual style for mood emojis.',
        weather_outline: 'Outline (Lucide)',
        weather_filled: 'Filled',
        weather_color: 'Colorful',
        weather_emoji: 'Emoji',
        weather_ascii: 'ASCII (Retro)',
        weather_thin: 'Thin',
        weather_bold: 'Bold',
        weather_cartoon: 'Cartoon',
        weather_mono_duotone: 'Mono Duotone',
        weather_neon: 'Neon',
        emoji_noto: 'Google Noto Color',
        emoji_noto_mono: 'Google Noto (Mono)',
        emoji_openmoji: 'OpenMoji',
        emoji_emojidex: 'Emojidex',
        emoji_native: 'Native (System)',
        emoji_grayscale: 'Grayscale',
        emoji_sepia: 'Sepia (Vintage)',
        emoji_neon: 'Neon (Glow)',
        emoji_pop: 'Pop Art (Vibrant)',
        emoji_soft: 'Soft (Pastel)',
        emoji_retro: 'Retro (Pixel)',
        emoji_glitch: 'Glitch',
        dark: 'Dark',
        light: 'Light',
        lavender: 'Lavender',
        system: 'System',
        custom: 'Custom',
        base: 'Base',
        accent: 'Accent Color',
        preview: 'Preview',
        apply_custom: 'Apply Custom Theme',
        font_family: 'Font Family',
        font_size: 'Font Size',
        upload_font: 'Upload Custom Font (.ttf, .woff)',
        upload_btn: 'Upload Font',
        font_placeholder: 'Select from list...',
        search_fonts: 'Search fonts...',
        custom_bg: 'Background Color'
    },
    settings: {
        title: 'Settings',
        save_settings: 'Save Settings',
        tabs: {
            general: 'General',
            views: 'Views',
            public: 'Public',
            account: 'Account',
            about: 'About',
            data: 'Data Management',
            layout: 'Layout'
        },
        theme: 'Theme',
        language: 'Language',
        display_name: 'Display Name',
        account_hint_name: 'e.g. Rea (Becomes: ReaLog)',
        admin_password: 'New Admin Password',
        admin_password_hint: 'Leave empty if unchanged',
        account_hint_pass: 'If left empty, the default (or previous) password remains active.',
        data_management: 'Data Management',
        delete_sample_data: 'Delete Sample Data',
        delete_sample_hint: 'Deletes only the sample entries created at installation.',
        reset_diary: 'Reset Diary',
        reset_hint: 'Deletes ALL entries but keeps settings.',
        backup_title: 'Backup & Restore',
        create_backup: 'Create Backup',
        restore: 'Restore',
        backup_hint: 'Saves to the "backups" folder on the server.',
        no_backups: 'No backups found.',
        restore_confirm: 'Are you sure you want to restore this backup? Current data will be overwritten.',
        reset_confirm: 'Are you SURE you want to delete all entries? This cannot be undone!',
        db_size: 'Current DB Size',
        public_settings: 'Public View Settings',
        public_atlas: 'Show Map (Atlas)',
        public_gallery: 'Show Gallery',
        hierarchical_view: 'Hierarchical View',
        hierarchical_hint: 'Configure whether higher-level views (e.g. Monthly) show entries from lower levels.',
        weekly_view: 'Weekly View Settings',
        monthly_view: 'Monthly View Settings',
        yearly_view: 'Yearly View Settings',
        inc_daily: 'Include Daily entries',
        inc_weekly: 'Include Weekly entries',
        inc_monthly: 'Include Monthly entries',
        features: 'Features',
        enable_stats: 'Show Statistics',
        enable_gamification: 'Show Gamification (Streak)',
        enable_habits: 'Show Habit Tracker',
        grid_layout: 'Grid View Layout',
        layout_standard: 'Standard (Row-based)',
        layout_masonry: 'Masonry (Pinterest-style)',
        writing_goals: 'Writing Goals',
        min_word_count: 'Minimum word count goal',
        show_word_count: 'Show word count in editor',
        checking_update: 'Checking for updates',
        new_version: 'New version available',
        uptodate: 'System is up to date',
        update_error: 'Error checking version',
        update_btn: 'Install Update',
        whats_new: 'What\'s New',
        layout_desc: 'Configure the order of the Entry Detail modal sections.',
        layout_header: 'Header (Title, Date, Weather)',
        layout_tags: 'Tags',
        layout_mood: 'Mood',
        layout_content: 'Content (Text / Questions)',
        layout_habits: 'Habits',
        layout_gallery: 'Gallery',
        dev_mode: 'Developer Mode'
    },
    update: {
        in_progress: 'Update in progress...',
        success: 'Update successful!',
        failed: 'Update failed',
        retry: 'Retry',
        step_backup: 'Backing up system...',
        step_download: 'Downloading files...',
        step_install: 'Installing new version...',
        backup_error: 'Failed to create system backup. Update aborted.'
    },
    tags: {
        manager_title: 'Tag Manager',
        manage_btn: 'Manage',
        back_btn: 'Back to Cloud',
        rename: 'Rename',
        delete: 'Delete',
        merge_hint: 'Renaming to an existing tag will merge them.',
        confirm_delete: 'Are you sure you want to delete this tag from all entries?',
        new_name_placeholder: 'New tag name...',
        rename_success: 'Tag renamed successfully!',
        delete_success: 'Tag deleted.',
        count: 'pcs'
    },
    status: {
        server_online: 'Server: Online',
        local_storage: 'Local Storage',
        saving: 'Saving...',
        auto_saving: 'Auto Saving...',
        save_error: 'Save Error!',
        saved: 'Saved',
        auto_saved: 'Auto Saved',
        ready: 'Ready',
        system_ok: 'System OK',
        tooltip: 'Click to switch storage mode and debug',
        log_title: 'System Log',
        log_tooltip: 'Click to open log',
        clear_log: 'Clear Log'
    },
    app: {
        loading_system: 'Starting System...',
        initializing: 'Initializing...',
        admin_login: 'Admin Login',
        password: 'Password',
        login_btn: 'Login',
        login_subtitle: 'Enter password to edit.',
        cloud_tags: 'Tag Cloud',
        no_tags: 'No tags yet. Use #hashtag in your entries!',
        entries_with_tag: 'Entries with tag:',
        on_this_day_title: 'On This Day',
        world_map: 'World Map',
        photo_gallery: 'Photo Gallery',
        new_entry: 'New Entry',
        no_entries: 'No entries to display.',
        click_plus: 'Click + to create a new entry.',
        wrong_password: 'Wrong password!',
        import_error: 'Error during import.',
        import_confirm: 'Are you sure you want to overwrite current data?',
        browser_no_geo: 'Browser does not support geolocation.',
        geo_error: 'Error getting location.',
        upload_error: 'Upload failed',
        file_too_large: 'File too large (max 5MB).',
        questions_tab: 'Questions',
        entries_tab: 'Entries',
        read_time: '{min} min read'
    },
    editor: {
        title: 'Title',
        title_placeholder: 'Entry Title...',
        mood: 'Mood',
        mode_structured: 'Questions (Grind)',
        mode_free: 'Free Diary',
        location_weather: 'Location & Weather',
        add_photo: 'Add Photo',
        change_photo: 'Change Photo',
        delete_location: 'Delete Location',
        delete_weather: 'Delete Weather',
        location_private: 'Location Private (Hidden from Map)',
        location_public: 'Location Public',
        free_text_placeholder: 'Write your thoughts here...',
        add_question: '+ Add Question...',
        response_placeholder: 'Write here...',
        private_entry: 'Private Entry (Admin only)',
        public_entry: 'Public Entry',
        save: 'Save',
        cancel: 'Cancel',
        words: 'words',
        location_picker: 'Select Location',
        save_location: 'Save Location (e.g. Home)',
        saved_locations: 'Saved Places',
        use_location: 'Select',
        location_name: 'Location Name',
        sort_by: 'Sort',
        sort_name: 'Name',
        sort_date: 'Date',
        map_preview: 'Map',
        insert_time: 'Insert Time',
        habits_title: 'Habits',
        weather_history_error: 'Failed to fetch weather data.',
    },
    questions: {
        title: 'Manage Questions',
        add_placeholder: 'Enter new question...',
        add_btn: 'Add',
        active: 'Active',
        inactive: 'Inactive',
        select_category: 'Select Category'
    },
    habits: {
        title: 'Manage Habits',
        add_new: 'Add New Habit',
        name_placeholder: 'Habit Name (e.g. Reading)',
        type_boolean: 'Boolean (Check)',
        type_value: 'Counter (Value)',
        unit_placeholder: 'Unit (e.g. cup)',
        goal_placeholder: 'Goal (e.g. 8)',
        active: 'Active',
        inactive: 'Inactive',
        icon: 'Icon',
        select_icon: 'Select Icon'
    },
    deploy: {
        title: 'Deploy ReaLog',
        subtitle: 'Own Server',
        guide: 'Guide',
        files: 'Server Files',
        manual_title: 'Run on your own server',
        step_1: 'Create a folder on your server (e.g. /naplo).',
        step_2: 'Download the source code (ZIP) and unzip it.',
        step_3: 'Check if img folder is created and writable (CHMOD 755/777).',
        step_4: 'Decide backend type (Node.js or PHP).',
        step_5: 'Save the selected code to the appropriate filenames.',
        note: 'Data is saved to separate files (entries.json, settings.json). If missing, system inits from default.*.json.',
        download_btn: 'Download Source Code (.zip)',
        zipping: 'Zipping...',
        no_data: 'No data included',
        copy: 'Copy',
        chmod_warning: 'CHMOD 755 required!',
        download_error: 'Download errors',
        zip_error: 'ZIP Error',
        clipboard_copied: 'Copied to clipboard!',
        lang_title: 'Add New Language',
        lang_step_1: 'Copy src/langs/hu.ts file (e.g. to de.ts).',
        lang_step_2: 'Translate strings and change registerLanguage call at the bottom.',
        lang_step_3: 'Open index.html and add the new file path to CRITICAL_FILES list.'
    },
    export: {
        title: 'Data Management',
        period: 'Period',
        all: 'All',
        custom: 'Custom',
        start: 'Start',
        end: 'End',
        format: 'Format (Local)',
        import: 'Import',
        import_placeholder: 'Upload JSON or WXR file',
        include_private: 'Include private entries',
        markdown_obsidian: 'Obsidian / Markdown (ZIP)',
        markdown_desc: 'Folder structure + .md files'
    },
    debug: {
        title: 'Switch Storage',
        connect: 'Connecting...',
        server: 'Own Server',
        server_desc: 'Use Node.js or PHP backend. Full sync.',
        local: 'Browser Memory',
        local_desc: 'Data stays on this device. Lost if cache cleared!',
        time: 'Time',
        place: 'Place',
        name: 'Name',
        save_auto: 'Save (Auto)'
    },
    server: {
        api_not_found: 'API not found (404)',
        server_error: 'Server Error (500)',
        http_error: 'HTTP Error',
        script_fail: 'Script failed to run',
        php_fail: 'PHP failed to run',
        json_fail: 'JSON parsing error',
        network_error: 'Network error',
        upload_restricted: 'Image upload is restricted on Node.js without extra libs.',
        missing_url: 'Cloud URL not configured',
        empty_response: 'Empty response from cloud',
        offline_mode: 'Offline Mode Active'
    }
};

registerLanguage('en', 'English', en);
