
import { registerLanguage } from '../services/i18n';

const hu = {
    common: {
        loading: 'Betöltés...',
        search: 'Keresés (#cimke is)...',
        save: 'Mentés',
        cancel: 'Mégse',
        delete: 'Törlés',
        edit: 'Szerkesztés',
        copy: 'Másolás',
        favorite: 'Kedvenc',
        yes: 'Igen',
        no: 'Nem',
        ok: 'OK',
        error: 'Hiba',
        success: 'Siker',
        confirm_delete: 'Biztosan a kukába helyezed?',
        confirm_perm_delete: 'Véglegesen törlöd? Ez nem vonható vissza!',
        confirm_discard: 'A bejegyzés a kukába kerül. Folytatod?',
        confirm_discard_changes: 'Elveted a változtatásokat? A bejegyzés nem lesz mentve.',
        confirm_action: 'Biztosan végrehajtod?',
        unsaved_changes: 'Nem mentett változások vannak! Ha kilépsz, a módosítások elvesznek. Biztosan folytatod?',
        draft: 'Vázlat',
        trash: 'Kuka',
        restore: 'Visszaállítás',
        perm_delete: 'Végleges törlés',
        empty_trash: 'A kuka üres.',
        empty_trash_btn: 'Kuka ürítése',
        confirm_empty_trash: 'Biztosan véglegesen törölsz MINDEN elemet a kukából?',
        jump_today: 'Ugrás a mára',
        good_morning: 'Jó reggelt',
        good_afternoon: 'Szép napot',
        good_evening: 'Szép estét'
    },
    category: {
        daily: 'Napi',
        weekly: 'Heti',
        monthly: 'Havi',
        yearly: 'Éves'
    },
    subcats: {
        general: 'Napomról',
        health: 'Egészség',
        friends: 'Barátság',
        business: 'Üzleti fejlődés',
        finance: 'Anyagi függetlenség',
        family: 'Család',
        personal: 'Személyes fejlődés',
        goals: 'Célok',
        dreams: 'Tervek álmok',
        achieved: 'Elért célok'
    },
    weather: {
        wmo_0: 'Tiszta égbolt',
        wmo_1: 'Túlnyomóan derűs',
        wmo_2: 'Változóan felhős',
        wmo_3: 'Borult',
        wmo_45: 'Köd',
        wmo_48: 'Zúzmarás köd',
        wmo_51: 'Szitálás: Gyenge',
        wmo_53: 'Szitálás: Mérsékelt',
        wmo_55: 'Szitálás: Sűrű',
        wmo_56: 'Ónos szitálás: Gyenge',
        wmo_57: 'Ónos szitálás: Sűrű',
        wmo_61: 'Eső: Gyenge',
        wmo_63: 'Eső: Mérsékelt',
        wmo_65: 'Eső: Erős',
        wmo_66: 'Ónos eső: Gyenge',
        wmo_67: 'Ónos eső: Erős',
        wmo_71: 'Havazás: Gyenge',
        wmo_73: 'Havazás: Mérsékelt',
        wmo_75: 'Havazás: Erős',
        wmo_77: 'Hódara',
        wmo_80: 'Zápor: Gyenge',
        wmo_81: 'Zápor: Mérsékelt',
        wmo_82: 'Zápor: Heves',
        wmo_85: 'Hózápor: Gyenge',
        wmo_86: 'Hózápor: Erős',
        wmo_95: 'Zivatar',
        wmo_96: 'Zivatar jégesővel (gyenge)',
        wmo_99: 'Zivatar jégesővel (erős)'
    },
    nav: {
        map: 'Térkép',
        gallery: 'Galéria',
        tags: 'Címkék',
        stats: 'Statisztika',
        on_this_day: 'Mai napon',
        settings: 'Beállítások',
        deploy: 'Telepítés',
        export: 'Export / Import',
        logout: 'Kijelentkezés',
        login: 'Admin belépés',
        entries: 'Bejegyzések',
        questions: 'Kérdések',
        habits: 'Szokások',
        appearance: 'Kinézet',
        menu: 'Menü',
        trash: 'Kuka',
        random: 'Véletlen emlék'
    },
    filters: {
        title: 'Részletes szűrők',
        date_start: 'Kezdet',
        date_end: 'Vége',
        mood: 'Hangulat',
        has_photo: 'Csak fotóval',
        clear: 'Szűrők törlése'
    },
    stats: {
        title: 'Statisztikák',
        total_entries: 'Összes bejegyzés',
        current_streak: 'Jelenlegi sorozat',
        longest_streak: 'Leghosszabb sorozat',
        mood_distribution: 'Hangulat eloszlás',
        activity_heatmap: 'Aktivitás (Utolsó 1 év)',
        no_data: 'Nincs elegendő adat a statisztikákhoz.',
        words: 'Szavak',
        chars: 'Karakterek',
        locations: 'Helyszínek',
        top_locations: 'Leglátogatottabb helyek',
        longest_entry: 'Leghosszabb',
        correlations: 'Összefüggések',
        weather_mood: 'Időjárás & Hangulat',
        day_mood: 'Napok & Hangulat',
        insight_weather: '{weather} időben a leggyakoribb:',
        insight_day: '{day} napokon a leggyakoribb:',
        streak_title: 'Kitartás & Lendület',
        streak_subtitle: 'A következetesség a siker kulcsa.',
        calendar_view: 'Naptár nézet'
    },
    templates: {
        title: 'Sablonok',
        save_current: 'Jelenlegi mentése sablonként',
        load: 'Sablon betöltése',
        name_placeholder: 'Sablon neve (pl. Edzés napló)',
        confirm_load: 'Ez felülírja a jelenlegi kérdéseket. Folytatod?',
        empty: 'Nincsenek mentett sablonok.',
        saved: 'Sablon mentve!',
        deleted: 'Sablon törölve.',
        set_default: 'Legyen alapértelmezett',
        is_default: '(Alapértelmezett)'
    },
    theme: {
        title: 'Kinézet Szerkesztő',
        subtitle: 'Válaszd ki a neked tetsző stílust vagy hozz létre sajátot.',
        presets: 'Témák',
        create: 'Létrehozás',
        typography: 'Tipográfia',
        weather_tab: 'Időjárás',
        emoji_tab: 'Hangulat',
        secret_tab: 'Titok (Ünnepek)',
        weather_desc: 'Válaszd ki, hogyan jelenjenek meg az időjárás ikonok az egész alkalmazásban.',
        emoji_desc: 'Válaszd ki a hangulatjelek (emojik) megjelenési stílusát.',
        weather_outline: 'Vonalas (Lucide)',
        weather_filled: 'Teli (Filled)',
        weather_color: 'Színes',
        weather_emoji: 'Emoji',
        weather_ascii: 'ASCII (Retro)',
        weather_thin: 'Vékony',
        weather_bold: 'Vastag',
        weather_cartoon: 'Rajzfilm',
        weather_mono_duotone: 'Monokróm (Árnyalt)',
        weather_neon: 'Neon',
        emoji_noto: 'Google Noto Color',
        emoji_noto_mono: 'Google Noto (Mono)',
        emoji_openmoji: 'OpenMoji',
        emoji_emojidex: 'Emojidex',
        emoji_native: 'Alap (Rendszer)',
        emoji_grayscale: 'Fekete-fehér',
        emoji_sepia: 'Szépia (Régies)',
        emoji_neon: 'Neon (Fényes)',
        emoji_pop: 'Pop Art (Élénk)',
        emoji_soft: 'Lágy (Pasztell)',
        emoji_retro: 'Retro (Pixel)',
        emoji_glitch: 'Glitch (Hiba)',
        dark: 'Sötét',
        light: 'Világos',
        lavender: 'Levendula',
        system: 'Rendszer',
        custom: 'Egyéni',
        base: 'Alap',
        accent: 'Kiemelő Szín',
        preview: 'Előnézet',
        apply_custom: 'Egyéni Téma Alkalmazása',
        font_family: 'Betűtípus',
        font_size: 'Betűméret',
        upload_font: 'Saját betűtípus feltöltése (.ttf, .woff)',
        upload_btn: 'Betűtípus Feltöltés',
        font_placeholder: 'Válassz a listából...',
        search_fonts: 'Betűtípus keresése...',
        custom_bg: 'Háttérszín'
    },
    settings: {
        title: 'Beállítások',
        save_settings: 'Beállítások Mentése',
        tabs: {
            general: 'Általános',
            views: 'Nézet',
            public: 'Publikus',
            account: 'Fiók',
            about: 'Rólam',
            data: 'Adatkezelés',
            layout: 'Elrendezés'
        },
        theme: 'Téma',
        language: 'Nyelv',
        display_name: 'Megjelenített Név',
        account_hint_name: 'pl. Rea (Ebből lesz: ReaLog)',
        admin_password: 'Új Admin Jelszó',
        admin_password_hint: 'Hagyd üresen, ha nem változtatod',
        account_hint_pass: 'Ha üresen hagyod, az alapértelmezett (vagy előző) jelszó marad érvényben.',
        data_management: 'Adatkezelés',
        delete_sample_data: 'Minta Adatok Törlése',
        delete_sample_hint: 'Csak a telepítéskor létrehozott példa bejegyzéseket törli.',
        reset_diary: 'Napló Alaphelyzetbe Állítása',
        reset_hint: 'Törli az ÖSSZES bejegyzést, de megtartja a beállításokat.',
        backup_title: 'Biztonsági Mentés',
        create_backup: 'Mentés Létrehozása',
        restore: 'Visszatöltés',
        backup_hint: 'Mentés a szerver "backups" mappájába.',
        no_backups: 'Nincsenek mentések.',
        restore_confirm: 'Biztosan visszaállítod ezt a mentést? A jelenlegi adatok felülíródnak.',
        reset_confirm: 'BIZTOSAN törölsz minden bejegyzést? Ez nem visszavonható!',
        db_size: 'Jelenlegi adatbázis méret',
        public_settings: 'Publikus Nézet Beállításai',
        public_atlas: 'Térkép (Atlasz) megjelenítése',
        public_gallery: 'Galéria megjelenítése',
        hierarchical_view: 'Hierarchikus Nézet',
        hierarchical_hint: 'Itt beállíthatod, hogy a magasabb szintű nézetek (pl. Havi) megjelenítsék-e az alacsonyabb szintű bejegyzéseket.',
        weekly_view: 'Heti Nézet Beállításai',
        monthly_view: 'Havi Nézet Beállításai',
        yearly_view: 'Éves Nézet Beállításai',
        inc_daily: 'Napi bejegyzések megjelenítése',
        inc_weekly: 'Heti bejegyzések megjelenítése',
        inc_monthly: 'Havi bejegyzések megjelenítése',
        features: 'Funkciók',
        enable_stats: 'Statisztikák megjelenítése',
        enable_gamification: 'Játékosítás (Streak) megjelenítése',
        enable_habits: 'Szokáskövető megjelenítése',
        grid_layout: 'Rács Nézet Elrendezés',
        layout_standard: 'Standard (Sorfolytonos)',
        layout_masonry: 'Masonry (Pinterest-szerű)',
        writing_goals: 'Írási Célok',
        min_word_count: 'Minimum elvárt szószám',
        show_word_count: 'Szószám mutatása szerkesztőben',
        checking_update: 'Frissítések keresése',
        new_version: 'Új verzió elérhető',
        uptodate: 'A rendszer naprakész',
        update_error: 'Hiba a verzió ellenőrzésekor',
        update_btn: 'Frissítés Telepítése',
        whats_new: 'Újdonságok',
        layout_desc: 'Itt állíthatod be a bejegyzések részletes nézetének (modális ablak) sorrendjét.',
        layout_header: 'Fejléc (Cím, Dátum, Időjárás)',
        layout_tags: 'Címkék',
        layout_mood: 'Hangulat',
        layout_content: 'Tartalom (Szöveg / Kérdések)',
        layout_habits: 'Szokások',
        layout_gallery: 'Galéria',
        layout_map: 'Térkép',
        map_size: 'Térkép mérete',
        map_small: 'Kicsi',
        map_medium: 'Közepes',
        map_large: 'Nagy',
        dev_mode: 'Fejlesztői Mód'
    },
    update: {
        in_progress: 'Frissítés folyamatban...',
        success: 'Sikeres frissítés!',
        failed: 'Frissítési hiba',
        retry: 'Újrapróbálkozás',
        step_backup: 'Biztonsági mentés készítése...',
        step_download: 'Fájlok letöltése...',
        step_install: 'Új verzió telepítése...',
        backup_error: 'Nem sikerült biztonsági mentést készíteni. A frissítés leállt.'
    },
    tags: {
        manager_title: 'Címkék',
        manage_btn: 'Kezelés',
        back_btn: 'Vissza a felhőhöz',
        rename: 'Átnevezés',
        delete: 'Törlés',
        merge_hint: 'Ha létező névre nevezed át, a címkék összeolvadnak.',
        confirm_delete: 'Biztosan törlöd ezt a címkét az összes bejegyzésből?',
        new_name_placeholder: 'Új címke név...',
        rename_success: 'Címke sikeresen átnevezve!',
        delete_success: 'Címke törölve.',
        count: 'db',
        view_cloud: 'Címkefelhő',
        view_list: 'Szerkesztés'
    },
    status: {
        server_online: 'Szerver: Online',
        local_storage: 'Helyi Tároló',
        saving: 'Mentés...',
        auto_saving: 'Auto mentés...',
        save_error: 'Mentési Hiba!',
        saved: 'Mentve',
        auto_saved: 'Auto Mentve',
        ready: 'Kész',
        system_ok: 'Rendszer OK',
        tooltip: 'Kattints a tárolási mód váltásához és hibakereséshez',
        log_title: 'Rendszernapló',
        log_tooltip: 'Kattints a napló megnyitásához',
        clear_log: 'Napló törlése'
    },
    app: {
        loading_system: 'Rendszer indítása...',
        initializing: 'Inicializálás...',
        admin_login: 'Admin Belépés',
        password: 'Jelszó',
        login_btn: 'Belépés',
        login_subtitle: 'Add meg a jelszót a szerkesztéshez.',
        user_not_found: 'Felhasználó nem található',
        cloud_tags: 'Címkefelhő',
        no_tags: 'Nincsenek címkék. Használd a #szó formátumot a bejegyzéseidben!',
        entries_with_tag: 'Bejegyzések ezzel a címkével:',
        on_this_day_title: 'Mai napon',
        world_map: 'Világtérkép',
        photo_gallery: 'Fotógaléria',
        new_entry: 'Új Bejegyzés',
        no_entries: 'Nincs megjeleníthető bejegyzés.',
        click_plus: 'Kattints a + gombra új bejegyzéshez.',
        wrong_password: 'Hibás jelszó!',
        import_error: 'Hiba az importálás során.',
        import_confirm: 'Biztosan felülírod a jelenlegi adatokat?',
        browser_no_geo: 'A böngésző nem támogatja a helymeghatározást.',
        geo_error: 'Hiba a helymeghatározás során.',
        upload_error: 'Hiba a feltöltés során',
        file_too_large: 'Túl nagy fájl (max 5MB).',
        questions_tab: 'Kérdések',
        entries_tab: 'Bejegyzések',
        read_time: '{min} perc olvasás',
        zen_mode: 'Fókusz mód',
        zoom_in: 'Nagyítás',
        zoom_out: 'Kicsinyítés'
    },
    editor: {
        title: 'Cím',
        title_placeholder: 'Adj címet...',
        mood: 'Hangulat',
        mode_structured: 'Kérdések (Grind)',
        mode_free: 'Szabad Napló',
        location_weather: 'Helyszín & Időjárás',
        add_photo: 'Fotó hozzáadása',
        change_photo: 'Fotó cseréje',
        delete_location: 'Helyszín törlése',
        delete_weather: 'Időjárás törlése',
        location_private: 'Helyszín privát (Térképen nem látszik)',
        location_public: 'Helyszín publikus',
        free_text_placeholder: 'Írd ide a gondolataidat...',
        add_question: '+ Kérdés hozzáadása...',
        response_placeholder: 'Írj ide...',
        private_entry: 'Privát bejegyzés (Csak admin látja)',
        public_entry: 'Publikus bejegyzés',
        save: 'Mentés',
        cancel: 'Mégse',
        words: 'szó',
        location_picker: 'Helyszín választása',
        save_location: 'Hely mentése (pl. Otthon)',
        saved_locations: 'Mentett Helyek',
        use_location: 'Kiválaszt',
        location_name: 'Hely neve',
        sort_by: 'Rendezés',
        sort_name: 'Név',
        sort_date: 'Dátum',
        map_preview: 'Térkép',
        insert_time: 'Idő beszúrása',
        habits_title: 'Szokások',
        weather_history_error: 'Az időjárás lekérése sikertelen.',
    },
    questions: {
        title: 'Kérdések kezelése',
        add_placeholder: 'Írj be egy új kérdést...',
        add_btn: 'Hozzáadás',
        active: 'Aktív',
        inactive: 'Inaktív',
        select_category: 'Válassz kategóriát'
    },
    habits: {
        title: 'Szokások Kezelése',
        add_new: 'Új szokás hozzáadása',
        name_placeholder: 'Szokás neve (pl. Olvasás)',
        type_boolean: 'Eldöntendő (Pipa)',
        type_value: 'Számláló (Érték)',
        unit_placeholder: 'Mértékegység (pl. pohár)',
        goal_placeholder: 'Cél (pl. 8)',
        active: 'Aktív',
        inactive: 'Inaktív',
        icon: 'Ikon',
        select_icon: 'Válassz ikont'
    },
    deploy: {
        title: 'ReaLog Telepítése',
        subtitle: 'Saját Szerver',
        guide: 'Útmutató',
        files: 'Szerver Fájlok',
        manual_title: 'Futtatás saját szerveren',
        step_1: 'Készíts egy mappát a szerveren (pl. /naplo).',
        step_2: 'Töltsd le a teljes forráskódot (ZIP) és csomagold ki.',
        step_3: 'Ellenőrizd, hogy az img mappa létrejön-e, és írható-e (CHMOD 755/777).',
        step_4: 'Döntsd el a backend típusát (Node.js vagy PHP).',
        step_5: 'Mentsd el a választott kódokat a megfelelő fájlneveken.',
        note: 'Az adatok külön fájlokba (entries.json, settings.json) mentődnek. Ha ezek hiányoznak, a rendszer a default.*.json fájlokból inicializál.',
        download_btn: 'Teljes Forráskód Letöltése (.zip)',
        zipping: 'Csomagolás...',
        no_data: 'Adatok (bejegyzések) nélkül',
        copy: 'Másolás',
        chmod_warning: 'CHMOD 755 kötelező!',
        download_error: 'Hibák a letöltés során',
        zip_error: 'ZIP Hiba',
        clipboard_copied: 'Vágólapra másolva!',
        lang_title: 'Új Nyelv Hozzáadása',
        lang_step_1: 'Másold le a src/langs/hu.ts fájlt (pl. de.ts-re).',
        lang_step_2: 'Fordítsd le a szövegeket, és a fájl végén módosítsd a registerLanguage("de", "Deutsch", ...) hívást.',
        lang_step_3: 'Nyisd meg az index.html-t, és add hozzá az új fájl elérési útját a CRITICAL_FILES listához.'
    },
    export: {
        title: 'Adatkezelés',
        period: 'Időtartam',
        all: 'Összes',
        custom: 'Egyéni',
        start: 'Kezdet',
        end: 'Vége',
        format: 'Formátum (Helyi)',
        import: 'Importálás',
        import_placeholder: 'JSON vagy WXR fájl feltöltése',
        include_private: 'Privát bejegyzések is',
        markdown_obsidian: 'Obsidian / Markdown (ZIP)',
        markdown_desc: 'Mappastruktúra + .md fájlok'
    },
    debug: {
        title: 'Tároló Váltás',
        connect: 'Kapcsolódás...',
        server: 'Saját Szerver',
        server_desc: 'Node.js vagy PHP backend használata. Teljes szinkronizáció.',
        local: 'Böngésző Memória',
        local_desc: 'Adatok csak ezen az eszközön. Cache törlésekor elveszhet!',
        time: 'Idő',
        place: 'Hely',
        name: 'Név',
        save_auto: 'Mentés (Auto)'
    },
    server: {
        api_not_found: 'API nem található (404)',
        server_error: 'Szerver Hiba (500)',
        http_error: 'HTTP Hiba',
        script_fail: 'Script nem futott le',
        php_fail: 'PHP nem futott le',
        json_fail: 'JSON feldolgozási hiba',
        network_error: 'Hálózati hiba',
        upload_restricted: 'Képfeltöltés Node.js alatt extra könyvtárak nélkül korlátozott.',
        missing_url: 'Nincs beállítva felhő URL',
        empty_response: 'Üres válasz a felhőből',
        offline_mode: 'Offline Mód Aktív'
    }
};

registerLanguage('hu', 'Magyar', hu);
