
export const GOOGLE_FONTS = [
    "Roboto", "Open Sans", "Montserrat", "Lato", "Poppins", "Inter", "Roboto Condensed", "Oswald", "Nunito", "Raleway", 
    "Ubuntu", "Merriweather", "PT Sans", "Playfair Display", "Rubik", "Mukta", "Lora", "Work Sans", "Nunito Sans", "Fira Sans", 
    "Quicksand", "Barlow", "Noto Sans", "Mulish", "PT Serif", "Inconsolata", "Titillium Web", "Kanit", "Heebo", "IBM Plex Sans", 
    "DM Sans", "Oxygen", "Karla", "Josefin Sans", "Libre Franklin", "Arvo", "Libre Baskerville", "Dosis", "Bitter", "Cabin", 
    "Anton", "Hind", "Manrope", "Dancing Script", "Source Code Pro", "Cairo", "Bebas Neue", "Pacifico", "Lobster", "Comfortaa", 
    "Crimson Text", "Exo 2", "Varela Round", "Fjalla One", "Abel", "Play", "Signika", "Bree Serif", "Architects Daughter", 
    "Righteous", "Amatic SC", "Indie Flower", "Shadows Into Light", "Abril Fatface", "Alfa Slab One", "Acme", "Permanent Marker", 
    "Fredoka One", "Cinzel", "Satisfy", "Courgette", "Great Vibes", "Sacramento", "Cookie", "Kalam", "Gloria Hallelujah", 
    "Patua One", "Crete Round", "Rokkitt", "Pathway Gothic One", "Rajdhani", "Chakra Petch", "Teko", "Orbitron", "Audiowide", 
    "Press Start 2P", "Unica One", "Carter One", "Passion One", "Luckiest Guy", "Bangers", "Chewy", "Special Elite", 
    "Coming Soon", "Covered By Your Grace", "Rock Salt", "Homemade Apple", "Nothing You Could Do", "Reenie Beanie", 
    "Waiting for the Sunrise", "Just Another Hand", "Nanum Pen Script", "Walter Turncoat", "Patrick Hand", "Neucha", 
    "Finger Paint", "Schoolbell", "Itim", "Pangolin", "Gaegu", "Gamja Flower", "Hi Melody", "Dokdo", "East Sea Dokdo", 
    "Gugi", "Black Han Sans", "Jua", "Do Hyeon", "Sunflower", "Gothic A1", "Nanum Gothic", "Nanum Myeongjo", 
    "Song Myung", "Noto Serif KR", "Noto Sans KR", "Noto Sans JP", "Noto Serif JP", "M PLUS 1p", "M PLUS Rounded 1c", 
    "Sawarabi Mincho", "Sawarabi Gothic", "Kosugi", "Kosugi Maru", "Zen Maru Gothic", "Zen Kaku Gothic New", 
    "Kiwi Maru", "Yusei Magic", "Train One", "DotGothic16", "RocknRoll One", "Reggae One", "Stick", "Klee One", 
    "Hachi Maru Pop", "Potta One", "Shippori Mincho", "Shippori Mincho B1", "Dela Gothic One", "Kaisei Decol", 
    "Kaisei HarunoUmi", "Kaisei Opti", "Kaisei Tokumin", "Yuji Boku", "Yuji Mai", "Yuji Syuku", "Hina Mincho", 
    "Zen Antique", "Zen Antique Soft", "Zen Old Mincho", "Zen Kurenaido", "Mochiy Pop One", "Mochiy Pop P One", 
    "Rampart One", "Bakbak One", "Grey Qo", "Rubik Glitch", "Rubik Wet Paint", "Rubik Distressed", "Rubik Puddles", 
    "Rubik Microbe", "Rubik Storm", "Rubik Vinyl", "Rubik Iso", "Rubik Marker Hatch", "Rubik Burned", "Rubik Pixels", 
    "Rubik 80s Fade", "Rubik Dirt", "Rubik Moonrocks", "Rubik Bubbles", "Rubik Gemstones", "Nabla", "Silkscreen", 
    "Aboreto", "Castoro Titling", "Cinzel Decorative", "Fauna One", "Uncial Antiqua", "MedievalSharp", 
    "Almendra", "Almendra Display", "Almendra SC", "IM Fell English", "IM Fell English SC", "Cardo", "EB Garamond", 
    "Sorts Mill Goudy", "Goudy Bookletter 1911", "Cormorant Garamond", "Proza Libre", "Cantarell", "Fira Sans Condensed", 
    "Fira Sans Extra Condensed", "Barlow Condensed", "Barlow Semi Condensed", "Roboto Slab", "Zilla Slab", "Josefin Slab", 
    "BioRhyme", "Space Mono", "Space Grotesque", "Syne", "Epilogue", "Sora", "JetBrains Mono", "Trispace", "Recursive", 
    "Fraunces", "Glory", "Zen Dots", "Michroma", "Gruppo", "Jura", "Electrolize", "Allerta Stencil", "Saira Stencil One", 
    "Black Ops One", "Quantico", "Share Tech Mono", "VT323", "Cutive Mono", "Fira Code", "Anonymous Pro", "Ubuntu Mono", 
    "Overpass Mono", "Oxygen Mono", "PT Mono", "Nova Mono", "B612 Mono", "Major Mono Display", "Xanh Mono", "Syne Mono", 
    "Courier Prime"
].sort();
